apiVersion: apps/v1
kind: Deployment
metadata:
  name: backoffice-deployment
  labels:
    app: backoffice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backoffice
  template:
    metadata:
      labels:
        app: backoffice
    spec:
      containers:
        - name: backoffice
          image: okteto.dev/backoffice
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
                limits:
                  memory: "3Gi"
                  cpu: "1000m"
          env:
            - name: VUE_APP_MAPS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: VUE_APP_MAPS_API_KEY
            - name: VUE_APP_API_URL
              value: "https://gateway-megaredhand.cloud.okteto.net/"

---
apiVersion: v1
kind: Service
metadata:
  name: backoffice-service
spec:
  selector:
    app: backoffice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
